### ISSUE TITLE
Autofac Example does not seem to be working

### ISSUE THREAD

**Issue by justinhomes** [ziyasal/RepositoryT.EntityFramework#3]
Other example like console app works but autofac example is not working. it gives empty console screen with no output. addUser does not seem to be persisting the data.

@ziyasal @ocinbat

**Comment by ocinbat** [comment]
Hi @justinhomes,

Thanks for letting us know the issue.

[This commit](https://github.com/ziyasal/RepositoryT.EntityFramework/commit/f80546d98f4c4ef35fe915c6c55b96b976698622) should fix it.
