### ISSUE TITLE
problem with async use

### ISSUE THREAD

**Issue by justinhomes** [ziyasal/RepositoryT.EntityFramework#5]
I used this framework with syntax below
await _repo.GetAll().ToListAsync() ;

When i make concurrent calls i get error below. it seems we return same dbcontext everytime and sample has defined repo class defined as singelton. what is the right solution for this approach?

A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.

**Comment by ocinbat** [comment]
Hi @justinhomes 

This is not an issue with the package.
It's a feature in EntityFramework and it's by deisgn.
If you would like to use async operations and fetch multiple queries simultaneously with the same context you should define multiple active result sets as true in your connection string.

For much more information see link below:

https://msdn.microsoft.com/library/h32h3abf(v=vs.110).aspx
